### ISSUE TITLE
Reducing file size

### ISSUE THREAD

**Issue by adowedar88** [airbnb/lottie#101]
Excuse me, my client wanted me to create a how-to-use animation for his app, so he can put it in the app when it first loads. The animation is 18 seconds long, so the file size is big (2.98 mb) .. I tried recreating the whole animation with a lower height compositions (cause I tried just down-scaling the final composition and it didn't work) and also it didn't work. Could you please help me reducing the file size? The client wants it just 700 pixels height and when I preview the json file on webflow it shows up with larger scale than that.
Thanks and sorry for bothering.

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)
