### ISSUE TITLE
web canvas render Alpha Inverted Matte issue

### ISSUE THREAD

**Issue by lusnaow** [airbnb/lottie#102]
plugin version: 5.5.9

svg render right

canvas render partially lost alpha channel

- svg:
<img width="1499" alt="svg" src="https://user-images.githubusercontent.com/8565744/67154614-10f64480-f332-11e9-9be4-c99f24f1133b.png">

- canvas:
<img width="1362" alt="canvas" src="https://user-images.githubusercontent.com/8565744/67154621-2f5c4000-f332-11e9-9bd0-c614b82a05b6.png">

[lottie_test.zip](https://github.com/airbnb/lottie/files/3747469/lottie_test.zip)

**Comment by bodymovin** [comment]
Hi, the canvas renderer doesn't support track matte masks for now

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.
