### ISSUE TITLE
LottieAnimationView instance state saving and restoration not working?

### ISSUE THREAD

**Issue by gajicm93** [airbnb/lottie#103]
I see that LottieAnimationView class has "save" and "restore" instance state implementation, but it is obviously not working properly? I have a very simple demo app, and when I rotate a screen or test with "don't keep activities" developer option, the animation starts from beginning, while it should resume from where it stopped according to implementation.

**Comment by madrazzl3** [comment]
> I see that LottieAnimationView class has "save" and "restore" instance state implementation, but it is obviously not working properly? I have a very simple demo app, and when I rotate a screen or test with "don't keep activities" developer option, the animation starts from beginning, while it should resume from where it stopped according to implementation.

Do you specified `android:id` tag for LottieView?

**Comment by gajicm93** [comment]
@madrazzl3 yes, I know about the trick.. Is this working for you properly or..? Cause I've tested it on 2 devices already and it's not working..

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-android.
