### ISSUE TITLE
Integrate in a html page a json file

### ISSUE THREAD

**Issue by Vincent-web** [airbnb/lottie#110]
After Effect 2020 - Bodymovin v5.5.8
I followed our workflow on https://airbnb.io/lottie/#/web
I have a message in my browser :
lottie.js:1 Access to XMLHttpRequest at 'file:///D:/CloudStation/Projets/KQT-Site/KQT-WebSite/jeux.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Note : I have no problem to export json file and make a html page only with 1 page, now I want to integrate in my workflow to import many _Lottie_ in several models.

**Comment by bodymovin** [comment]
Hi, for security reasons, browsers don't allow loading json files through our file system. You need to use a web server.

**Comment by Vincent-web** [comment]
Thank you, but why there is a possibility to make one html file with a local preview ?

**Comment by bodymovin** [comment]
If you mean the demo.html, it's because the json file gets bundled as part of the html instead of being a separate file.

**Comment by Vincent-web** [comment]
OK, I'll do with it.

**Comment by Vincent-web** [comment]
Unfortunately it does not work
I download on a server my html... the json animation is missing on my page, nothing inside the console.

**Comment by bodymovin** [comment]
can you share a link?

**Comment by Vincent-web** [comment]
No I can't, my work is confidential

**Comment by bodymovin** [comment]
Without more context I can't help further.
If you can share a link with a similar case that doesn't compromise your work, I can take a look.

**Comment by Vincent-web** [comment]
Sure, it isn't easy to show my case study.

**Comment by Vincent-web** [comment]
The issue is fixed, the script for open ( lottie.js and index.js ) must be written at the end of the body html  not in the head.
