### ISSUE TITLE
Filled path is exported as path without fill

### ISSUE THREAD

**Issue by elenniko** [airbnb/lottie#111]
The circle in the wifi icon is filled in the ae file, but when exported with bodymovin it's just outlines.

https://lottiefiles.com/share/MN26DA

**Comment by bodymovin** [comment]
Hi, I guess it's related to merge paths.
Can you share the .aep?

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.
