### ISSUE TITLE
Large lottie file size

### ISSUE THREAD

**Issue by jonblomgren** [airbnb/lottie#114]
Hi all,

I'm relatively new to lottie, and noticing that my exported animation is much larger than I anticipated (5.5mb). I'm assuming this is due to a large number of individual shape layers (upwards of 70), and was curious if there are any tips/tricky on how I can decrease the size by an order of magnitude :). I've attached a reference still in case it's helpful.

Thanks!
Jon
<img width="712" alt="Screen Shot 2020-02-18 at 10 30 20 AM" src="https://user-images.githubusercontent.com/59071445/74766368-0ee9b700-523a-11ea-8d1b-28ae957ac9c6.png">

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
That filesize seems too large.
Anyway, if you gzip it served from your server, it should be much lighter

**Comment by jonblomgren** [comment]
Yeah I definitely can. I've attached it here.
Thanks for any help you can give.

[BetterUp - Website Animations - Fireworks - Final.aep.zip](https://github.com/airbnb/lottie/files/4222892/BetterUp.-.Website.Animations.-.Fireworks.-.Final.aep.zip)

**Comment by bodymovin** [comment]
In your composition `falling stars 1` you have a lot of layers with baked expressions with keyframes exceeding the duration of the layer.
I have deleted all the unnecessary keyframes and file size was reduced to 1Mb
After compression it was reduced to 60Kb

**Comment by jonblomgren** [comment]
Wow... That's amazing. Are you able to share the AEP file? I'd love to check it out

**Comment by bodymovin** [comment]
[BetterUp - Website Animations - Fireworks - Final.zip](https://github.com/airbnb/lottie/files/4228310/BetterUp.-.Website.Animations.-.Fireworks.-.Final.zip)
here you go

**Comment by artseabra** [comment]
Hey @bodymovin , anyway you can help me do the same? Somehow my json came out to like 25MB.

[Confetti Lottie Folder copy.zip](https://github.com/airbnb/lottie/files/4874172/Confetti.Lottie.Folder.copy.zip)

**Comment by vijaypwr61** [comment]
> In your composition `falling stars 1` you have a lot of layers with baked expressions with keyframes exceeding the duration of the layer.
> I have deleted all the unnecessary keyframes and file size was reduced to 1Mb
> After compression it was reduced to 60Kb

could you elaborate more?

**Comment by bodymovin** [comment]
@artseabra you are using an image sequence, unfortunately I don't think there is much to be done in that scenario. Perhaps you can try enabling compression.

**Comment by bodymovin** [comment]
@vijaypwr61 what do you mean?

**Comment by vijaypwr61** [comment]
@bodymovin I didn't get cleary your this statement.

> you have a lot of layers with baked expressions with keyframes exceeding the duration of the layer.
I have deleted all the unnecessary keyframes

**Comment by bodymovin** [comment]
@vijaypwr61 if you have your expressions baked into keyframes in your project, make sure you don't have unnecessary extra keyframes outside the bounds of the animation time

**Comment by vijaypwr61** [comment]
Thank you

**Comment by zachary-oas** [comment]
Hi @bodymovin I am also very new to lottie file format. When I export it out to lottie format it will be 18mb. In gif format I have it down to 16mb. What am I doing wrong. My use case is to have this up on website. 
[Final1.zip](https://github.com/airbnb/lottie/files/5378130/Final1.zip)

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)
