### ISSUE TITLE
Animation freeze after scrolling the recycler view

### ISSUE THREAD

**Issue by StephanShareChat** [airbnb/lottie#121]
I have used the lottie animation in my recycler item view , I showing the animation only for the first item of the recycler view , But after scrolling the recycler view the lottie animation got freeze. Can you guys please help me out.

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-android.
