### ISSUE TITLE
Individual and Employer Contributors License Agreements

### ISSUE THREAD

**Issue by jpventura** [airbnb/lottie#122]
Since this library is used by Airbnb [Android][google-play] and [iOS][app-store], I wonder if it would not be better require to sign _a contributor license agreement_ similar to Google [individual][cla-individual] and [employer][cla-employer] agreements :thinking:.

At Google projects, the CLAs are enforced by a [GitHub plugin][cla-assistant] triggered at [pull requests][pull-request], protecting the open-source projects from any possible litigations.

[app-store]: https://apps.apple.com/us/app/airbnb/id401626263
[cla-assistant]: https://github.com/cla-assistant/cla-assistant
[cla-individual]: https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_INDIVIDUAL
[cla-employer]: https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_CORPORATE
[github]: https://github.com/airbnb
[google-play]: https://play.google.com/store/apps/details?id=com.airbnb.android
[pull-request]: https://github.com/android/architecture-samples/pull/701

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)
