### ISSUE TITLE
Bodymovin Plugin - Wordpress

### ISSUE THREAD

**Issue by Kromian** [airbnb/lottie#125]
Hello GitHub World.

I am not a coder by any stretch; I get by on plugins. The Bodymovin plugin for Wordpress as stopped working and I have tried all the suggestions on other threads to try and get it to work, meaning:
1. I have replaced the lottie.js file with the 5.9.6 version (also did this with the lottie.min.js file)
2. I have updated the AE plugin to the 5.9.6 version

I'm not sure if there is anything else that I need to do to get it working.  Is there a Guide for Dummies that someone can give me that will get this up and running with the latest WP version. I have seen that some people have gotten it to work doing some code things, and what I have done already, with no luck...But I am eager to learn.

Please could someone advise me here?
Many thanks
Kromian

**Comment by bodymovin** [comment]
Hi, have you tried the lottiefiles web player?
https://lottiefiles.com/web-player

**Comment by Kromian** [comment]
> Hi, have you tried the lottiefiles web player?
> https://lottiefiles.com/web-player

@bodymovin Thanks for the response...
I have, however, I find that it (or I) has limited capabilities. I want the video/animation to play only on scrolling, and for it to be used in Slider Revolution. From what I understand, this could be done using the bodymovin plugin. 
Can this be don't with the lottiefile player?

**Comment by bodymovin** [comment]
I think the Wordpress plugin is not being maintained anymore.
You can always load it manually but if you are not familiar with code, it might be complicated.
I don't know of Wordpress limitations.

**Comment by Kromian** [comment]
Yeah...I guess I have to find someone who could do this for me. Thank you @bodymovin
