### ISSUE TITLE
currentFrame and goToAndStop method issue + playTo method

### ISSUE THREAD

**Issue by JuZED** [airbnb/lottie#126]
Hi !

Awesome library !

I want to make an interactive animated button with lottie and I like to know if it's possible to implement an `anim.playTo(value, isFrame)`?

As a workaround, I tried something like: 

```
animateTo = (to) => {
    console.log("Anim From: ", myanim.currentFrame, " To: ", to);
    
    if(myanim.currentFrame === to) {
        console.log("no changes");
        
        return;
    }

    myanim.playSegments(
        [
            myanim.currentFrame,
            to,   
        ], true
    );
}
```

Furthermore, it seems that:
- `myanim.currentFrame` is not always the last visible frame,
- `myanim.goToAndStop(myframe, true)` does not stop where it should.

You can see what I'm trying to do [here](https://playcode.io/595777/).

Thanks !

Julien

**Comment by JuZED** [comment]
Hi !

And thanks @bodymovin for not responding...
I found it by myself, by adding my own library to lottie.js

Thanks again for your great support !!

Julien

**Comment by bodymovin** [comment]
Sorry for taking longer than you expected in responding.
I maintain this project in my spare time and sometimes there are other priorities.
Contributions are always welcome if you have also time to help others.
Glad you could sort it out.

**Comment by JuZED** [comment]
No worries, I finally did it by myself. Sorry I was a bit mad (you answered a guy in one hour and no answer for me in 4 days...)  but I understand your position.
By the way, I had to do this because there is an issue with `currentFrame` and `gotToAndStop` after a complete loop.. the animation goes crazy. 
FYI, my library, that use lottie.js, plays the animation frame by frame so I manage to go threw the loop issue. Furthermore, it seems that the `complete` event comes to early in the animation, so I had to add a timer if the event is quicker than the frame duration... a bit tricky but it works since this morning with a smooth animation with whom I can interact to go forward, backward, loop, ....

Thank again,

Julien

**Comment by bodymovin** [comment]
The way loops work is complex if you have subframe rendering turned on and loop set to true.
I can't see the project because it's no longer valid, but my guess it that is what seems to behave strangely.
If you are handling very specific frame events I usually suggest to call `anim.setSubframe(false);` and not use `loop: true` if possible

**Comment by JuZED** [comment]
Hi,

You can see what I was trying to do [here](https://playcode.io/600364/).
But with or without loops (line 68 of scripts) and with `useSubFrames` set to `false`, same result...
