### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by wsdwsd0829** [airbnb/lottie#127]
1. Is there RTL support for flipping the animation or a lottie view? 
we currently flip the view ourselves through view.transform. 

2. A more complex request similar to android that we can support rtl per composition layer in case there are text in one layer which we do not want to flip. 
https://github.com/airbnb/lottie-android/issues/1145

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on the applicable platforms.
