### ISSUE TITLE
Show a specific frame on initial load

### ISSUE THREAD

**Issue by hakkim** [airbnb/lottie#128]
Hi,
I have a lottie animation that I have integrated it in my code. I want to show a specific frame on initial load and when the user hover it the animation should start from the beginning and completes it.

This is what I want to show in first load -  
![image](https://user-images.githubusercontent.com/7419977/81442042-7d327b80-9190-11ea-865b-317edadda0f0.png)
And this is the completed animation - 
![image](https://user-images.githubusercontent.com/7419977/81442101-95a29600-9190-11ea-80d5-52b22eaa24ed.png)

This is my code
```
let iconMenu = document.querySelector('.bodymovinanim1');
let animationMenu = bodymovin.loadAnimation({
    container: iconMenu,
    renderer: 'svg',
    loop: false,
    autoplay: false,
    path: "https://assets2.lottiefiles.com/packages/lf20_txJcSM.json",
});
animationMenu.addEventListener('DOMReady',function(){
    animationMenu.playSegments([1,200],true);
});
iconMenu.addEventListener('mouseover', (e) => {
    animationMenu.play();
});
```

[This is my fiddle](https://jsfiddle.net/hakkim/cd5r1q7w/2/)

Can any one please help me?

**Comment by bodymovin** [comment]
hi, can you ask this question in lottie-web?
https://github.com/airbnb/lottie-web

**Comment by hakkim** [comment]
> hi, can you ask this question in lottie-web?
> https://github.com/airbnb/lottie-web

Sure... Sorry for bothering
