### ISSUE TITLE
Support for Tapered Strokes in After Effects 17.01

### ISSUE THREAD

**Issue by bricklane** [airbnb/lottie#130]
After Effects v17 now supports tapered strokes, it would be great to get this supported in Lottie.js.

**Comment by mosttriumphant** [comment]
+1. The guys behind Rubberhose just released a new tapered preset as well- would love to see support for this! @bricklane  If your design can support the extra performance necessary, this script seems to be working for Lottie tapered strokes in the meantime.  https://www.youtube.com/watch?v=YwC009ESmZI

**Comment by bodymovin** [comment]
Unfortunately tapered stroke doesn't translate to anything on svg or canvas so the implementation is complex and would probably have a big performance impact.
I've searched for solutions but there are none that seem promising.
For now there is no plan on supporting it.

**Comment by mbasaglia** [comment]
Could we have format support for this, even if most renderers won't support it?

**Comment by bodymovin** [comment]
@mbasaglia do you mean adding it to the exported json?

**Comment by mbasaglia** [comment]
Ye, even if not by bodymovin at least having a way of encoding that info in the json

**Comment by mbasaglia** [comment]
The reason it would be helpful for me is that I'm the maintainer of python-lottie which can output to inkscape and synfig files, both support tapered strokes

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.

**Comment by mbasaglia** [comment]
@gpeal I think this is more a format specs issue than a library issue, what would be the best repo for that?

**Comment by gpeal** [comment]
@mbasaglia lottie-web as I mentioned.
