### ISSUE TITLE
My json animation file is too large I can't upload it on web, Can I reduce the file size?

### ISSUE THREAD

**Issue by elifresiroglu** [airbnb/lottie#131]
I have a really complex animation done with after-effects and it has to be uploaded on the web the file size is 31 MB. What should I do?

**Comment by elifresiroglu** [comment]
https://drive.google.com/drive/folders/1MHDzuIamXszO2jkDqedfzAHUmYnieyXT?usp=sharing

Here is the file. Our developer said the file can't be uploaded.

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by elifresiroglu** [comment]
> hi, can you share the .aep?

Hello! Thank you for the answer. We found a way to save it differently right now it is 4mb but now we have an issue that we can't put it fullwidth in order to insert some links on the animation. Here is the file:https://drive.google.com/drive/u/0/folders/1lfY_nnIp_oJr7PXN9kNeu6DGzZo50_50
And this is the screen shot how it show on html
<img width="1300" alt="Screen Shot 2020-06-12 at 14 11 21" src="https://user-images.githubusercontent.com/66659299/84501329-9dd18200-acb6-11ea-8183-e88f805afddf.png">

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.
