### ISSUE TITLE
Android Motionlayout support

### ISSUE THREAD

**Issue by MartinRGB** [airbnb/lottie#132]
1.Android native drawing is more effective than lottie’s custom drawing
2.By using motionlayout animation,designer can easily handoff animation files，and developer can develop without thirdparty library like lottie

**Comment by gpeal** [comment]
1. Lottie does the exact same drawing as Android. It's all backed by the same Skia renderer.
I'm not sure what you're request is. MotionLayout and Lottie solve very different problems. If you have a more specific request, please open it on lottie-android.
