### ISSUE TITLE
The future of Lottie?

### ISSUE THREAD

**Issue by Tr736** [airbnb/lottie#133]
I notice lots of updates previous the big redundancy and wondered what the future looks like for Lottie?

**Comment by gpeal** [comment]
@Tr736 Can you explain? I don't understand your question.

**Comment by Tr736** [comment]
As Airbnb are the backers of this amazing framework I wanted to know how and if it will still  be supported after so many redundancies.

**Comment by gpeal** [comment]
@Tr736 Yes, none of us have worked for Airbnb in years and continue to maintain it. I left over 2 years ago!
