### ISSUE TITLE
Problem with sides of 3D cube

### ISSUE THREAD

**Issue by mersan-la** [airbnb/lottie#134]
Hi! I'm new here. I've problems when import my json file to lottie preview. 
I was create a 3D cube in After Effects. This cube working perfectly as well after effects as the html file, but don't way in lottie previews. 
The problem is that some sides doesn't see. It's probably i don't know how to use the coordenates, so... can someone help me? I'll be so grateful because I've been on this many hours. 

Thank you! 

PS: I share the zip file, if someone wants/needs to see it..
[Cube3D.zip](https://github.com/airbnb/lottie/files/4869077/Cube3D.zip)

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.
