### ISSUE TITLE
Weird shape auto-orient problem

### ISSUE THREAD

**Issue by ision-industries** [airbnb/lottie#136]
Hi everyone, I need your help. I have a simple shape layer animation animating position around a path with the auto-orient option turned on. There is a problem while playing back the animation on the Lottiefiles app for iOS and Android. The shape does not auto-orient along the path. But when I playback the animation in the mobile browser on my iOS and android devices the animation works as it should be as you can tell by the screenshots. My question is that if the animation plays back properly on the web then am I able to publish it?

Heres how the animation is supposed to look
![Proper Shape Orienting](https://user-images.githubusercontent.com/58711145/90032018-ea701400-dc8b-11ea-8bae-c5358b95857e.gif)

This screenshot is from the Lottiefiles mobile app
![Android Screenshot - Not orienting](https://user-images.githubusercontent.com/58711145/90031311-13dc7000-dc8b-11ea-86df-4d0a8f8f6874.jpg)

This screenshot is from the mobile browser
![Android Screenshot - Orienting](https://user-images.githubusercontent.com/58711145/90031344-1e970500-dc8b-11ea-974f-969d6381cc82.jpg)

The animation plays back perfectly fine on MacOS and windows as well. 

Windows
![Faux 3D phone Lottiefiles Expanded Card - Windows](https://user-images.githubusercontent.com/58711145/90031512-500fd080-dc8b-11ea-9e6b-57680e9623d3.png)

MacOS
<img width="2018" alt="3d Faux Phone Lottiefiles Thumbnails - iMac" src="https://user-images.githubusercontent.com/58711145/90031554-5d2cbf80-dc8b-11ea-9122-d6988e6e5b21.png">

**Comment by bodymovin** [comment]
hi, can you report this on the lottie-ios or lottie-android repos?
