### ISSUE TITLE
"Lottie_iOS" Carthage build not happening for Xcode 12 

### ISSUE THREAD

**Issue by devildriver666** [airbnb/lottie#138]
carthage update --platform iOS
*** Fetching lottie-ios
*** Checking out lottie-ios at "1692cb4d0fcf0406dcaf61bf7cafea49dca51354"
*** xcodebuild output can be found in /var/folders/z2/g_4hgnzn27vfcwdmmds43fc00000gn/T/carthage-xcodebuild.rerAM7.log
*** Building scheme "Lottie_iOS" in Lottie.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/abhijeetupadhyay/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/lottie-ios/1692cb4d0fcf0406dcaf61bf7cafea49dca51354/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Lottie.framework/Lottie /Users/abhijeetupadhyay/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/lottie-ios/1692cb4d0fcf0406dcaf61bf7cafea49dca51354/Build/Products/Release-iphonesimulator/Lottie.framework/Lottie -output /Users/abhijeetupadhyay/_workarea/lean-tech/SDK/link-sdk-ios/Carthage/Build/iOS/Lottie.framework/Lottie

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/z2/g_4hgnzn27vfcwdmmds43fc00000gn/T/carthage-xcodebuild.rerAM7.log

**Comment by devildriver666** [comment]
Above Error was with "master" branch. with general 
carthage update --platform iOS
*** Fetching lottie-ios
*** Checking out lottie-ios at "3.1.8"
*** xcodebuild output can be found in /var/folders/z2/g_4hgnzn27vfcwdmmds43fc00000gn/T/carthage-xcodebuild.2hWJ2k.log
*** Building scheme "Lottie_iOS" in Lottie.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/abhijeetupadhyay/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/lottie-ios/3.1.8/Build/Intermediates.noindex/ArchiveIntermediates/Lottie_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Lottie.framework/Lottie /Users/abhijeetupadhyay/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/lottie-ios/3.1.8/Build/Products/Release-iphonesimulator/Lottie.framework/Lottie -output /Users/abhijeetupadhyay/_workarea/lean-tech/SDK/link-sdk-ios/Carthage/Build/iOS/Lottie.framework/Lottie

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/z2/g_4hgnzn27vfcwdmmds43fc00000gn/T/carthage-xcodebuild.2hWJ2k.log

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-ios.
