### ISSUE TITLE
Laggy Full Viewport Animation Issue

### ISSUE THREAD

**Issue by bryanbenaim** [airbnb/lottie#139]
Hi I'm new to this so pardon if this is an obvious question: I've made a full viewport animation in AE that I'm planning to use for a website. The idea is that each "wave layer" will slide out of frame as you scroll. 

Issues:

When I render the JSON file with an SVG renderer, the frame rate is smooth (at smaller break points) until the viewport is maximized on my monitor, where it begins to lag quite heavily. To help reduce the file size, I've messed with the resolution and frame rate and used parenting but it doesn't seem to help much.

When I use a canvas renderer, the animation runs smoothly at all viewport sizes, but I lose the drop shadow effect.

When I forgo JSON for pure HTML/CSS, It runs smoothly as well, but cannot figure out how to stack the different animation layers (Z-index issue perhaps?). 

Any advice would be helpful! I'm attaching the relevant AE file and a sample HTML and JSON for reference. Thanks!

[Home Page Prototype.zip](https://github.com/airbnb/lottie/files/5368742/Home.Page.Prototype.zip)

[Layer_01  test.zip](https://github.com/airbnb/lottie/files/5368746/Layer_01.test.zip)

[Layer_04%20%20test.zip](https://github.com/airbnb/lottie/files/5368749/Layer_04.20.20test.zip)

![ezgif com-gif-maker](https://user-images.githubusercontent.com/70962849/95812936-3f57f700-0cdc-11eb-9f9b-7a77a301948f.gif)

**Comment by bodymovin** [comment]
Hi, unfortunately Drop Shadow have a big impact on performance. Specially on Safari and Firefox.
And having so many of them that are that large will not perform well on large screen sizes.
Regarding a pure HTML/CSS solution, can you share an example?

**Comment by bryanbenaim** [comment]
@bodymovin Hey Hernan, thanks for the reply. Let me see if I can be as detailed/clear as possible:

When I say "pure HTML/CSS", what I mean is, from body movin, I export a demo file (for in browser viewing). I take that code and input in into an HTML widget on Wordpress (within the plug-in, Elementor). When I duplicate these HTML widgets and (attempt to) stack them accordingly (altering Z-Indices, and having a fixed position on the page), the result is the GIF I'm attaching. None of the waves are layering appropriately and are duplicating unnecessarily. 

However with this method, I've noticed no lag (could be because they are not all in the viewport at the same time?) in comparison to pasting the JSON code into several Lottie widgets, and stacking it this way. I imagine this has something to do with the code and I'm a little in over my head.

I'm attaching all the wave HTML's that export directly from body movin. I've been copying only the script at the very bottom of each of these (into the HTML widget). 

Please let me know what you recommend:
-If the HTML route is a viable option (assuming I can get them to stack) that's ideal. 
-If not I may have to decrease the amount of drop shadow and reduce the size of these (less ideal).
-Let me know of any work around you can think of too. I've thought of rendering the drop shadows separately as a Gif (resolution not as important). Not sure if this would help or hurt.

P.S.
I have eliminated some shapes from the AE file (A larger shape per layer with 0% opacity to allow the drop shadows to render appropriately). The result is in a GIF below. The animation performs much better, and each JSON is now about half the size it was. Is there any way to adjust the filter size within the JSON files so the shadow is not clipped? I'm attaching The JSON files used.

Thanks, sorry if this is confusing!

[HTML Layers.zip](https://github.com/airbnb/lottie/files/5396178/HTML.Layers.zip)

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/70962849/96349785-7da43c00-1077-11eb-85ed-e9b462210143.gif)

[Layers  - Clipped Drop Shadow.zip](https://github.com/airbnb/lottie/files/5396236/Layers.-.Clipped.Drop.Shadow.zip)


![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/70962849/96350403-40da4400-107b-11eb-99a7-9e9caf70974b.gif)

**Comment by bodymovin** [comment]
Hi, unfortunately I can't think of a good solution for this.
Chrome doesn't support css filters for svgs, but firefox does.
So you'll need to use the svg native filters which have a performance cost.
Stacking multiple animations will probably impact performance even worse once you have them all rendering at the same time, and not to mention that they might get out of sync and filesize will incrase significantly doing it the way you plan to.
