### ISSUE TITLE
Lottie content beyond what was created for my lottie file

### ISSUE THREAD

**Issue by mmdock** [airbnb/lottie#155]
Using a lottie file designed as shown below:

<img width="727" alt="Screen Shot 2021-03-02 at 4 45 21 PM" src="https://user-images.githubusercontent.com/2423465/109735087-fdd6c400-7b76-11eb-9383-e8507a59b508.png">

However, when rendering it edge to edge in my code with an AnimationView, it appears to continue creating a rainbow and generating a bottom edge of the rainbow on the right and left sides, as seen below:

<img width="343" alt="Screen Shot 2021-03-02 at 4 45 28 PM" src="https://user-images.githubusercontent.com/2423465/109735082-fca59700-7b76-11eb-8af1-5db2f4b3bb08.png">

I would expect the rainbow to have been stretched instead of lottie.... calculating? more to the rainbow to show.

Any help or tips on how to resolve this behavior would be great

**Comment by bodymovin** [comment]
hi, can you share the .aep and a link with the implementation?

**Comment by mmdock** [comment]
@bodymovin  hey! so, this was only happening on devices with a width of 414 pts or greater

original:
Using [SnapKit](https://github.com/SnapKit/SnapKit) to make constraints:
``` Swift
        rainbowAnimation.snp.makeConstraints { make in
            make.left.right.equalToSuperview()
            make.bottom.equalTo(self.view.snp.centerY).offset(-20)
            make.centerX.equalToSuperview()
        }
```

fix:
``` Swift
        rainbowAnimation.snp.makeConstraints { make in
            make.left.right.equalToSuperview()
            make.height.equalTo(220)
            make.bottom.equalTo(self.view.snp.centerY).offset(-20)
            make.centerX.equalToSuperview()
        }
```

I actually kinda solved it?  I had to add a height. Once I set a height, it worked as I expected.   My guess is that without a height it assumes the default that the lottie was designed for and generates more of the rainbow vector arc?

Interesting things is that heights less than 220, like 200, start introducing the issue again.  

The behavior I would expect would be that, since it is designed to be edge to edge and setting it up like that, that lottie would resize the height as needed

I believe this is the file used:
https://lottiefiles.com/share/w2b54ptt

**Comment by bodymovin** [comment]
hi, I just noticed this seems to be an issue on the lottie-ios player. Can you post it on that repo?
This repo is just for the docs on airbnb.io/lottie
https://github.com/airbnb/lottie-ios
