### ISSUE TITLE
Lottie animation recompose bug 

### ISSUE THREAD

**Issue by 02gaurav** [airbnb/lottie#179]
I am using `LottieAnimation` in compose, its working except there is one issue. Recomposition happening very frequently. Not sure if it's a bug. Code that i am using is given below: 
**@Composable
fun ErrorScreen() {
    val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(R.raw.no_internet))
    val progress by animateLottieCompositionAsState(composition, iterations = LottieConstants.IterateForever)
    Column {
        LottieAnimation(composition, progress, alignment = Alignment.TopCenter)
    }
}**

**Comment by linhttbk** [comment]
i'm facing too

**Comment by 02gaurav** [comment]
@linhttbk It will recompose if you are using `iterations = LottieConstants.IterateForever`. I dont think this is a bug.
