### ISSUE TITLE
ReactXP Lottie Wrapper

### ISSUE THREAD

**Issue by colmbrady** [airbnb/lottie#20]
Hi Lottie team,

Great work on this product. Just letting the team know I have started a Lottie wrapper for ReactXP. The wrapper can run Lottie files on web and native via the ReactXP runtime.

https://github.com/colmbrady/lottie-reactxp

**Comment by bodymovin** [comment]
Hi, this is great! I didn't know about ReactXP.
If you need anything, let us know.

**Comment by gpeal** [comment]
Awesome! I added a link in 1cdba7aaec3bd7b461740786cb4ca466b984986e
