### ISSUE TITLE
Weird table of contents for ios/macos

### ISSUE THREAD

**Issue by ptxmac** [airbnb/lottie#212]
When expanding the ios/mac section of the docs the outline is looking very strange:

![image](https://user-images.githubusercontent.com/56919/207056425-5e5db92a-8e76-4029-a337-e71d239cf8b2.png)

**Comment by ptxmac** [comment]
It looks like there's been a PR to fix that waiting for a merge for one and a half year... #171

**Comment by calda** [comment]
This is fixed now, thanks
