### ISSUE TITLE
Problem with sides of 3D cube

### ISSUE THREAD

**Issue by Navajocoding** [airbnb/lottie#213]
Hi! I'm new here. I've problems when import my json file to lottie preview. I was create a 3D cube in After Effects. This cube working perfectly as well after effects as the html file, but don't way in lottie previews. The problem is that some sides doesn't see. It's probably i don't know how to use the coordenates, so... can someone help me? I'll be so grateful because I've been on this many hours.
Thank you!
PS: I share the zip file, if someone wants/needs to see it..

[MOTION.aep.zip](https://github.com/airbnb/lottie/files/10251522/MOTION.aep.zip)

**Comment by bodymovin** [comment]
hi, 3d has limited support by lottie. But if it works in the html file and not on the lottie preview, you might need to change the renderer to html to fix it

**Comment by Navajocoding** [comment]
Hi there, many thanks for your answer.  Could you kindly provide me an
example in a codepen or something similar?
That would be great


Il giorno mar 10 gen 2023 alle ore 02:03 hernan ***@***.***>
ha scritto:

**Comment by bodymovin** [comment]
here's the wiki page for it
https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#renderer-default-is-svg
I'm closing this issue. If you need to follow up on it, please open a new ticket in the lottie-web repository.
https://github.com/airbnb/lottie-web
