### ISSUE TITLE
scale and position lottie animations within an SVG object

### ISSUE THREAD

**Issue by isaacalves** [airbnb/lottie#23]
I've been in pain for two days trying to add animated SVG objects inside an SVG path. I was finally able to do it with Lottie.

Now I'm struggling to find a way to set the size and relative coordinates on which the animated object with Lottie will be positioned/rendered within the parent SVG.

Is that possible?

**Comment by bodymovin** [comment]
Hi, I haven't worked much with svgs inside other svgs.
Do you have a link of what you're trying to do and can you share where you got so far?

**Comment by gpeal** [comment]
This should be on the lottie-web repo
