### ISSUE TITLE
Render to SketchApp

### ISSUE THREAD

**Issue by LincMitch** [airbnb/lottie#28]
Can Lottie use SketchApp to render Sketch files?
As talked about here: https://github.com/airbnb/react-sketchapp/issues/239

I realise it's an animation, but the ability to render one frame makes sense to me.

**Comment by gpeal** [comment]
@LincMitch  @buba447 has written a [Sketch to Lottie plugin](https://github.com/buba447/Lottie-Sketch-Export)
