### ISSUE TITLE
Stroke Color property cannot have eases

### ISSUE THREAD

**Issue by Sergio-Tomasa** [airbnb/lottie#36]
Hi, 

Just that, not a big issue, but in case someone has this trouble and is tracking the error, try using linear  interpolation. I guess it can happen in other properties.

Thanks

**Comment by bodymovin** [comment]
Hi, can you share an .aep with the issue? I just tested it and it seems to be working fine.

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
Please reopen this issue on lottie-web.
