### ISSUE TITLE
Performance is poor

### ISSUE THREAD

**Issue by chrsalctra** [airbnb/lottie#41]
I'm sure my 2017 MacBook isn't the issue. I cannot find anything to fix the FPS. Can someone check this out? It's a simple stroke draw in AE. Thank you.
[christian.zip](https://github.com/airbnb/lottie/files/1998220/christian.zip)

**Comment by bodymovin** [comment]
@chrsalctra Hi, can you post the issue on the lottie-web repository?
https://github.com/airbnb/lottie-web
