### ISSUE TITLE
Broken animation with turbolinks in a rails environment

### ISSUE THREAD

**Issue by WillDosSantos** [airbnb/lottie#42]
Hello,
(Disclaimer: New to lottie and dev. Forgive my poor phrasing and terminology)
**Context:**
Not sure if this is the correct place to post my issue but here it goes.
I'm working in a rails environment on a rather large application and trying to replace the loaders.
The loader is it's own React component. I have a page within my app with three tabs that I need to transition between.

**Issue:**
When the animation first loads, it works fine. However, if I transition between one tab to the other, the loader breaks. I'm not really sure how to solve this and I was wondering if anyone has encountered this problem before. 

Thanks!

**Gif of my animation breaking**:
![loading-mess-up](https://user-images.githubusercontent.com/1126074/40671334-6e7c69de-6320-11e8-8429-b01064913c74.gif)

**Comment by WillDosSantos** [comment]
@bodymovin Thanks for the reply. I'm not able to share the project unfortunately :( However good news I seemed to have just had an outdated version of lottie before. I updated it and that fixed the issue but there was still the issue of the animation loading on top itself in the console. So I just called:
```
  componentWillUnmount() {
    this.animation.destroy()
  }
```
within the component and that seems to have fixed the issue entirely.

**Comment by kevinthompson** [comment]
@bodymovin I took a look at this issue with @WillDosSantos internally. In our case, on each Turbolinks page load, a React component was being mounted to display that loader. When the component mounted it would call `bodymovin.loadAnimation` with the animation data and we were ending up with several of the same animation registered.

We're not sure why the additional copies of the animation caused the visual issues displayed in the gif, but the solution was to call `destroy` on the animation in the components `componentWillUnmount` lifecycle method.
