### ISSUE TITLE
Unity Support

### ISSUE THREAD

**Issue by EarMaster** [airbnb/lottie#43]
Is there support for importing Lottie animations into Unity?

We currently fall back to use exported sprite sheets to import animations from After Effects into Unity. This has disadvantages such as the inability to automatically import complex animation without manual optimization (stripping duplicate frames) and an increased file size.

**Comment by bodymovin** [comment]
Hi, not yet unfortunately.
I don't know the capabilities of Unity, but would it need some kind of Unity specific renderer or how would that work?

**Comment by EarMaster** [comment]
Unity has - as a 3D game engine - it's own animation system able to control every property of the controlled object. So I think this would have to be the basis for an importer.

It should be no problem to use PNG files as they can easily be imported as Sprites. There currently is no native importer for SVG (also there are open source implementations and the Unity dev team is working on this for an upcoming release), but it is possible to draw vector shapes using LineRenderers.

@Unity-Technologies may be able to provide you with further information and maybe even a cooperation as this would be a good addition to the existing toolchain.

**Comment by monsdar** [comment]
That would be a very useful thing to have. Currently there only are Assets in the Unity Asset Store that can convert from AE to sprites ([example](https://assetstore.unity.com/packages/tools/animation/ae2unity-after-effect-to-unity-animation-44618)).

**Comment by tonzari** [comment]
(Sorry to post to an old thread, but I believe this is relevant to many googlers who may end up here)

@EarMaster 

Umovin (https://github.com/leetful/U.movin) is a Lottie style framework for Unity! Personally, I've had trouble with it, but perhaps it will work well for you.

"Inspired by Lottie frameworks that take animation data from After Effects to create animated vector sequences for web/mobile. With the help of the Vector Graphics package, this library aims to bring the same and more to Unity."

**Comment by pixelsage** [comment]
This would be splendid.

**Comment by markadrake** [comment]
Hi everyone! I'm working in Unity but not as familiar with it (the editor, the game engine, capabilities, terminology, etc) but I have been tasked with delivering concepts for how our UI will work. I was hoping, like much of you, that what I've learned about animation on the web, mobile, and desktop apps (thanks AirBnb) would easily translate to Unity.

I'd love to tackle this issue with other members from the community if you'd like to develop a Unity library for working with the Bodymovin JSON files. Could we perhaps discuss what level of effort and where we would need to start to accomplish this?

**Comment by tonzari** [comment]
Have you already reached out to https://github.com/leetful ?

**Comment by gpeal** [comment]
**Closing all library issues and feature requests on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

**Comment by fitzeekdrew** [comment]
> Hi, not yet unfortunately.
> I don't know the capabilities of Unity, but would it need some kind of Unity specific renderer or how would that work?

Then why are you even responding? That’s his entire question; obviously he doesn’t know ‘how that would work’ 🤦‍♂️

**Comment by bodymovin** [comment]
@fitzeekdrew you are right, my bad, thank you.
