### ISSUE TITLE
Bounce expression doesn't work in Lottie Preview on iOS

### ISSUE THREAD

**Issue by robitgraphesc** [airbnb/lottie#50]
Hi folks,

I have an issue that I attached a bounce expression to an asset's scale in my AE project, which works great in the preview of lottiefiles.com both on desktop and mobile, but the bounce expression is lost when I open it through the QR code in the iOS preview app.

I asked my team to test it for themselves and it works perfectly through the shared link both on Windows and Mac desktops and both on Android and iOS mobiles' browsers (Chrome, Firefox and Safari too).

I attached the AE project file and the json too in a zip. Hope you can help what's this issue with the iOS preview.

Cheers,
Tibor

[starAE_aep-json.zip](https://github.com/airbnb/lottie/files/2154756/starAE_aep-json.zip)

**Comment by bodymovin** [comment]
Hi, expressions are not supported by the ios and android players.
You can try baking them into keyframes if it works for your case.

**Comment by robitgraphesc** [comment]
Oh, I see! Thanks for the response.
