### ISSUE TITLE
Xcode Product > Analyze Issues

### ISSUE THREAD

**Issue by omidontop** [airbnb/lottie#53]
Having encountered EXC_BAD_ACCESS crashes a few times I ran a Product > Analyze on my project and the only issues Xcode found were with the lottie. I hereby list them all in two different categories:

## Memory error
- /.../Pods/lottie-ios/lottie-ios/Classes/Private/LOTComposition.m:115:19: nil passed to a callee that requires a non-null 3rd parameter
- /.../Pods/lottie-ios/lottie-ios/Classes/Private/LOTComposition.m:120:19: nil passed to a callee that requires a non-null 3rd parameter
- /.../Pods/lottie-ios/lottie-ios/Classes/Private/LOTComposition.m:125:3: nil passed to a callee that requires a non-null 1st parameter
## Logic error
- /.../Pods/lottie-ios/lottie-ios/Classes/AnimatableLayers/LOTCompositionContainer.m:41:9: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue
- /.../Pods/lottie-ios/lottie-ios/Classes/AnimatableLayers/LOTLayerContainer.m:83:7: Converting a pointer value of type 'NSNumber * _Nullable' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

I'm using Xcode 9.4.1 and lottie-ios 2.5.0.

**Comment by gpeal** [comment]
@omidontop Please post this on lottie-ios.
