### ISSUE TITLE
Use Lottie to display cross platform static graphics?

### ISSUE THREAD

**Issue by oisinlavery** [airbnb/lottie#57]
My team is currently exploring the use of Lottie to display static icons across all our platforms (web, iOS, Android).

We can achieve this now but it requires piping the icons through After Effects which is a slow process and as far as I know isn't automatable. Ideally I'd like to convert from SVG to JSON and have Lottie consume that.

Could someone point me to documentation around the JSON structure Lottie uses.

**Comment by gpeal** [comment]
@oisinlavery Unfortunately, After Effects is the best way right now. [These](https://github.com/airbnb/lottie-web/tree/master/docs/json) are also the best docs for the json. We would very much like to improve them though!
