### ISSUE TITLE
http://airbnb.io/lottie gives 404

### ISSUE THREAD

**Issue by mrbm** [airbnb/lottie#61]
link in the instructions of this github repo: http://airbnb.io/lottie returns a 404

**Comment by ljharb** [comment]
It loads for me, and for [everyone else](https://downforeveryoneorjustme.com/airbnb.io)?

**Comment by mrbm** [comment]
I am seeing it load now...but I swear I test 4 different times 2-3 hours ago. Weird! Side now...what about something for flutter.io ...is that in the works?
