### ISSUE TITLE
json file size could be smaller

### ISSUE THREAD

**Issue by lbenedetto** [airbnb/lottie#63]
I noticed a lot of repeated strings in my exported JSON file.
For example
ADBE Vector Group, ADBE Vector Graphic - Fill, ADBE Vector Shape - Group occur a total of 300 times in my animation.

I replaced these strings with the acronyms: AVG, AVGF, AVSG, and my animation file was 5kb smaller.

Whatever code is generating the JSON file should be minifying it as well. 

I've ran into performance issues before with Lottie due to large file sizes. Granted, just shrinking by 5KB isn't going to fix anything on its own, but it certainly can't hurt.

**Comment by bodymovin** [comment]
Hi, there is work being done in opting out of some of the properties.
But unless you are using expressions, renaming them shouldn't break the animation.
Can you share the project so I can take a look?
Regarding large file sizes, what kind of performance issues are you facing?
Usually gzipping the files reduces it to 10 to 20% of it's original filesize.

**Comment by lbenedetto** [comment]
I was wrong, it doesn't break the animation. I changed something else that broke it haha.

Performance issues were because the file was around 1.5MB. I told the art guy to use less layers and anchor points and stuff, and he got it down to 200kb and now it runs fine.

**Comment by bodymovin** [comment]
Was it 1.5MB compressed?

**Comment by lbenedetto** [comment]
Uncompressed. We're using it for Android, so its stored on the device, not being sent over the network.

**Comment by bodymovin** [comment]
I see
but AFAIK, Android compresses assets during the build process, right?

**Comment by lbenedetto** [comment]
I'm not sure actually. Does that matter?

**Comment by lbenedetto** [comment]
Yeah, the animation would load fast, but then play very choppily

**Comment by lbenedetto** [comment]
If anyone else cares, I wrote a Kotlin utility to shrink the file
```
import java.io.*
import java.nio.file.Files
import java.nio.file.Paths
import java.util.*

fun main(args: Array<String>) {
	System.out.print("Enter filename to optimize: ")
	val filename = Scanner(System.`in`).nextLine()

	val file = BufferedWriter(FileWriter(filename.replace(".json", "") + "_optimized.json"))

	Files.readAllLines(Paths.get(filename)).forEach { line ->
		var optimizedLine = line.replace("ADBE Vector Shape - Group", "VSG")
		optimizedLine = optimizedLine.replace("ADBE Vector Filter - Merge", "VFM")
		optimizedLine = optimizedLine.replace("ADBE Vector Graphic - Fill", "VGF")
		optimizedLine = optimizedLine.replace("ADBE Vector Graphic - Stroke", "VGS")
		optimizedLine = optimizedLine.replace("ADBE Vector Shape - Ellipse", "VSE")
		optimizedLine = optimizedLine.replace("ADBE Vector Group", "VG")
		optimizedLine = optimizedLine.replace("Shape Layer ", "SL")
		optimizedLine = optimizedLine.replace("Ellipse ", "E")
		optimizedLine = optimizedLine.replace("Path ", "P")
		file.write(optimizedLine)
	}

	file.close()
}
```

**Comment by gpeal** [comment]
I'm going to close this as this option and the option to remove unused transform properties is or will soon be added to the plugin. Also, lottie-web is the correct forum for this.
