### ISSUE TITLE
Add links to lottie-qml

### ISSUE THREAD

**Issue by Evil-Spirit** [airbnb/lottie#66]
I have tested and it is works for me!
https://sea-region.github.com/kbroulik/lottie-qml

**Comment by Evil-Spirit** [comment]
Also, it will be supported by QT https://www.phoronix.com/scan.php?page=news_item&px=Qt-5.13-Alpha-Released

**Comment by gpeal** [comment]
@Evil-Spirit That is also lined under Operating Systems
