### ISSUE TITLE
Old lib name (bodymovin) is exposed in the official page

### ISSUE THREAD

**Issue by heejongahn** [airbnb/lottie#67]
I'm not sure if this is the right place to file this issue, but I coulnd't find anywhere more appropriate.

At the [Get Started section](https://airbnb.design/lottie/#get-started) of the official homepage, `bodymovin` link actually (correctly) redirects to `lottie-web`. So I guess the displayed name and the link should be changed to `lottie-web`, too?

Or, if the link is supposed to point the bodymovin AE plugin, then maybe separate two links – bodymovin and lottie? I don't have a much of a context here so... just suggesting :) Thanks for the wonderful project btw. It's making my (and my team's) life much easier.

**Comment by ljharb** [comment]
It's definitely supposed to be renamed; a PR to fix it would be most appreciated.

**Comment by heejongahn** [comment]
@ljharb My initial thought was to file an PR for that too, but I couldn't find the repository related to https://airbnb.design/lottie. (yes, there were many occurrences of the word 'bodymovin' in this repo too but it all seemed irrelevant to the official landing page) Is there any (public) repo for the site?

**Comment by ljharb** [comment]
No. I’ll ask around internally.

**Comment by gpeal** [comment]
@ljharb @heejongahn Bodymovin is still the name of the After Effects plugin. The web player has been renamed to Lottie Web though.
