### ISSUE TITLE
Build.gradle problem

### ISSUE THREAD

**Issue by BostyBro** [airbnb/lottie#7]
After adding lottie to build.gradle file saying Error:Failed to resolve: com.android.support:appcompat-v7:26.1.0
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:F:/Crygram/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by adirzoari** [comment]
same issue, did you find solution?

**Comment by BostyBro** [comment]
@adirzoari Yes, i just added maven to my build.gradle file

**Comment by Aruvansh1997** [comment]
Hi can you please add the location and how to add maven in the file
