### ISSUE TITLE
Add a button skip/replay on a BodyMovin Animation ?

### ISSUE THREAD

**Issue by MeijeB** [airbnb/lottie#72]
Hi,

I'm new in using BodyMovin/Lottie and a real newbie in everything code related (other than HTML/CSS).

For my new job (yeah !), i've made an animation in AE (wich work like a charm once exported with Bodymovin, truly a wonderfull tool) and i'm looking to add next to this animation a replay/Skip button (a strong demand from my bosses).

Is it possible to add a separate HTML/CSS button that can control the animation ? I've been looking on the documentation and...i'm lost.  This is beyond my current understanding....

Should a forget it or Is it possible? If yes, does someone have an example that i can look at ?

Thank you for your attention,
Meije

**Comment by bodymovin** [comment]
hi, yes you can control the animation attaching behavior to a button in your page.
It Depends on how you loaded the animation, so if you have an example of what you have so far, I can try giving you some guidance.

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-web.
