### ISSUE TITLE
Animation does not start, when the Chrome tab is not active

### ISSUE THREAD

**Issue by xe4me** [airbnb/lottie#76]
Hi 
Much appreciation for your revolutionary framework.
I'm reporting a possible bug, where the animation does not start when the Chrome tab is not active.

You can easily replicate this by opening this link in the background [Rocket](https://lottiefiles.com/4999-rocket) see the rocket always starts moving only after you focus on the tab, whereas in Firefox, the rocket has started moving already.

This is a big problem for us because we're using Lottie animation in our splash screen and unless you've passed the splash screen, you won't see the application obviously, and when our users opening multiple tabs, they're excepting the application to be loaded when to go and focus on a tab, whereas, it will only start showing them the splash screen.

Thanks.

**Comment by bodymovin** [comment]
Lottie relies on `requestAnimationFrame ` to render each frame. Browsers have different policies regarding it's behavior when the current window is not focused.
If you need the animation to play when the window is not focused, you can roll out your own player leveraging `setInterval` that should work even when the window is not focused.
Or you can listen to window.focus and window.blur events to advance the animation to the position you want.

**Comment by xe4me** [comment]
I ended up hacking the `requestAnimationFrome` like below : 

```
if (document.hidden) {
        let lastTime = 0;
        window.requestAnimationFrame = function (callback) {
            let currTime = new Date().getTime();
            let timeToCall = Math.max(0, 16 - (currTime - lastTime));
            let id = setTimeout(function () {callback(currTime + timeToCall);}, timeToCall);
            lastTime = currTime + timeToCall;
            return id;
        };
    }
    anim.play();
    anim.onComplete = function () {
        
        window.requestAnimationFrame = originalAnimationFrame;
    }

```
