### ISSUE TITLE
Link to performance documentation broken.

### ISSUE THREAD

**Issue by MothusiMasibi** [airbnb/lottie#80]
The [link](http://airbnb.io/lottie/#/android/performance) to performance docs returns a `404`

**Comment by hrossi** [comment]
We have the same problem to the supported features link:

**Comment by hrossi** [comment]
http://airbnb.io/lottie/#/after-effects/supported-features

**Comment by rogercotrina** [comment]
Hello @gpeal, do you happen to know if those links were moved or completely removed?

**Comment by gpeal** [comment]
@rogercotrina It's still there, the link just changed
http://airbnb.io/lottie/#/android?id=performance

**Comment by rogercotrina** [comment]
Great. Thanks for validating @gpeal
