### ISSUE TITLE
Strange bug exporting animated stroke

### ISSUE THREAD

**Issue by Denizax** [airbnb/lottie#81]
I have a weird problem when exporting an animation with Bodymovin. 

I have applied a moving stroke effect to an autro trace later and it seems that the stroke doesn't move as in my project file when I test my .json file.

I saw that Bodymovin partially supports Stroke. Is that the problem and how can I fix this?

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
The stroke effect is partially supported indeed, but I can take a look.

**Comment by gpeal** [comment]
@Denizax This repo is just for documentation. Please post it on the repo for your platform.
