### ISSUE TITLE
When use in android,IllegalArgumentException: Key times and values must be the same length 

### ISSUE THREAD

**Issue by bboyban** [airbnb/lottie#90]
when i export in android to use,it was waring [IllegalArgumentException: Key times and values must be the same length ] ；
when i select export option [old json fomat],it no waring,but anmate was dont play,it cant work~???

**Comment by gpeal** [comment]
**Closing all library issues on this repo**
This repo is just for the docs on [airbnb.io/lottie](https://airbnb.io/lottie)

Please reopen this issue on lottie-android.
