### ISSUE TITLE
Mask inverted in AE not supported

### ISSUE THREAD

**Issue by megwehrlen** [airbnb/lottie#92]
Just wanted to add this out there as it can facilitate animators' process by knowing exactly what is supported and what isn't. 
**Masks are, but masks inverted are not**

They get switched to regular masks at export, which is fine, but it wasn't clear and can be a pretty heavy task to fix for complex animations.
It would be valuable to have it in the documentation to save iterations.
Thank you!

**Comment by bodymovin** [comment]
Hi, what inverted masks are you referring to?
Track matte masks or regular masks?

**Comment by megwehrlen** [comment]
Regular masks, so on the same layer as the shape masked, by using the invert checkbox.

**Comment by bodymovin** [comment]
Right, inverted masks are not supported in the svg renderer, but they are supported in the canvas renderer.
The Svg renderer has some support of subtracting masks (if the layer is not scaled), that can, in some cases behave like an inverted mask.

**Comment by megwehrlen** [comment]
I'll remember that! Thank you!
