### ISSUE TITLE
Added an animation on the submit GravityForm button

### ISSUE THREAD

**Issue by Carylgithub** [airbnb/lottie#95]
Hello,

I discovered your plugin and your complete solution only a few days ago and I wanted to thank you and congratulate you for what you have created! Without exaggerating, I think you will be the future of websites!
Congratulations again!

For your information, I use the **GravityForm** plugin on **Wordpress**, an equally powerful solution and I hope to be able to integrate all svg animations on all form interactions.

For this reason I have just asked for a development mission on the GravityForm community and on Codeable.

If you know developers who know these 2 solutions do not hesitate to forward these links where I detail the whole development project

[Gravity Forum](https://community.gravityforms.com/t/added-an-animation-on-the-submit-gravityform-button/2533)

[Codeable](https://app.codeable.io/tasks/107203)

In the long run I would really like to tell everyone how to easily integrate Lottie into GravityForm

I started by making an **animated logo**,
Then I'll try to integrate **Ajax spinners** 
Finally, it may be possible to replace all the submission buttons!

Once again, congratulations and thank you!

**Comment by gpeal** [comment]
I'm glad you like Lottie! This repo is just for the Lottie documentation. You might want to bring this up with the owners of those two sites though.
