### ISSUE TITLE
Mask problem

### ISSUE THREAD

**Issue by alexcasche** [airbnb/lottie#96]
Hey,

My designer is having a problem when rendering an animation in After Effects using the Bodymovin plugin. He is using a mask, which I believe is where the problem is occurring. I understand that the plugin doesn't handle masks well, so I've attached the working file to find a solution! Thank you

Will send the AEP file privately.

**Comment by chrisathomer** [comment]
Hi!

I'm making an assumption. So, I apologize...
We adjusted our approach to make sure we're only using additive masks and
haven't had many (maybe any) masking problems.
If you use any subtraction masks or some other Boolean combinations, see if
the visuals can be re-made with additive-only masks (if masks must be used).

**Comment by alexcasche** [comment]
Our designer is out of town, but he believes that the setup in After Effects should be fine to render, any chance you could take a look at it for us and help come up with a solve?

**Comment by bodymovin** [comment]
@alexcasche where have you shared the .aep?

**Comment by alexcasche** [comment]
Could we connect via email?

**Comment by bodymovin** [comment]
@alexcasche can we follow this issue here?
https://github.com/airbnb/lottie-web
You'll fin my email there as well.
